baseURL = "https://pion.ly"
languageCode = "en-us"
title = "Pion"
theme = "vanilla-bootstrap-hugo-theme"

# Uncomment below to enable syntax highlighting
# pygmentsCodefences = true
# pygmentsCodefencesGuessSyntax = true
# See https://xyproto.github.io/splash/docs/all.html for more styles
# pygmentsStyle = "pygments"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.nav]]
    name = "Blog"
    url = "/blog/"
    weight = 1
  [[menu.nav]]
    name = "Documentation"
    url = "/about/"
    weight = 2

[params]
  includeBootstrapJs = false
  showActiveNav = true
  containerMaxWidth = "100%"
  dateFormat = "Jan 2, 2006"
  hideFooter = false
