baseURL = "pion.ly/"
languageCode = "en-us"
title = "Pions"
theme = "minimal"

[params]
    author = "Pion Team"
    profilePic = "logo.png"
    description = "Building Blocks for Realtime Communication"
    githubUsername = "pions"
    accent = "#e53935"
    showBorder = true
    backgroundColor = "white"
    font = "Quicksand"
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go"]

[[menu.main]]
    url = "/docs/"
    name = "Docs"
    weight = 3

[[menu.main]]
    url = "/about/"
    name = "What's Pions?"
    weight = 3

[[menu.icon]]
    url = "mailto:team@pion.ly"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "http://gophers.slack.com/messages/pion"
    name = "slack"
    weight = 2

[[menu.icon]]
    url = "https://github.com/pions/"
    name = "github"
    weight = 3
