baseURL = "https://pion.ly"
defaultContentLanguage = "en"
languageCode = "en-us"
title = "Pion"
theme = "vanilla-bootstrap-hugo-theme"

[taxonomies]
  tag = "tags"

[menu]
  [[menu.nav]]
    name = "Blog"
    url = "/blog/"
    weight = 1
  [[menu.nav]]
    name = "Knowledge Base"
    url = "/kb/"
    weight = 2

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1

[params]
  includeBootstrapJs = false
  showActiveNav = true
  containerMaxWidth = "100%"
  dateFormat = "Jan 2, 2006"
  hideFooter = false
